version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: marketplace_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PSWD}
      MYSQL_DATABASE: marketplace
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: marketplace_redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: marketplace_app
    depends_on:
      - mysql
      - redis
    ports:
      - "7777:7777"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_PSWD: ${DB_PSWD}
      EMAIL: ${EMAIL}
      EMAIL_SENDER: ${EMAIL_SENDER}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/marketplace
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PSWD}

volumes:
  mysql_data: