spring.datasource.url=jdbc:mysql://mysql:3306/marketplace
spring.datasource.username=root
spring.datasource.password=${DB_PSWD}
#redis
#spring.redis.host=redis
#spring.redis.port=6379
jwt.secret=${JWT_SECRET}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false