# Database
spring.datasource.url=jdbc:localhost://mysql:3306/techJob
spring.datasource.username=root
spring.datasource.password=${LOCAL_PSWD}

#waiting time
spring.datasource.hikari.connectionTimeout=60000
spring.datasource.hikari.initializationFailTimeout=60000

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#port
server.port=7777
#jwt
jwt.secret=${JWT_SECRET}
jwt.access.expiration=3600000
jwt.refresh.expiration=7

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
#logging
spring.output.ansi.enabled=ALWAYS
logging.level.org.springframework.security=DEBUG
logging.level.org.springdoc=DEBUG
logging.level.root=INFO
logging.level.org.springframework=DEBUG
logging.level.com.techJob=DEBUG
#image
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
#email 
spring.mail.username=${EMAIL}
spring.mail.password=${EMAIL_SENDER}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#payment
spring.payment.url="/api/v1/payment/mock/"
system.public.id=""