package com.techJob.domain.enums;

public enum OrdersStatus {

	PENDING_ARTISAN_ACCEPTANCE,
    ACCEPTED,
    REJECTED,
    COMPLETED,
    CANCELED,
    IN_PROGRESS,
    ACCEPTED_PENDING_PAYMENT, DISPUTED,
    CANCELED_BY_ARTISAN,
    CANCELED_BY_CUSTOMER,
	
	
	
}
